define(`NOTICE_FOR_MACRO_PREPROCESSOR', `<!---
This file is generated by a macro preprocessor.
Dont edit this file directly but make changes in 
to the source document in macros/ 
-->')

define(m4_comment)
m4_comment(`Keep SQS disabled by default for now, enable if required.')
undefine(ENABLED_SQS)