define(`NOTICE_FOR_MACRO_PREPROCESSOR', `<!---
This file is generated by a macro preprocessor.
Dont edit this file directly but make changes in 
macros/Deployment Steps/default.md
-->')

define(PLATFORM_NAME, `IBM Cloud for VMware Solutions Dedicated (VCS)')
changequote(`~start', `~end')
include(Deployment Steps/default.md)